const RESEND_API_KEY = process.env.RESEND_API_KEY;
const CONTACT_EMAIL_FROM = process.env.CONTACT_EMAIL_FROM;
const CONTACT_EMAIL_TO = process.env.CONTACT_EMAIL_TO;

export { CONTACT_EMAIL_FROM, CONTACT_EMAIL_TO, RESEND_API_KEY };
